Traceback (most recent call last):
  File "sendmail.py", line 14, in <module>
    with open(r'database_auth.json','r') as readfile:
FileNotFoundError: [Errno 2] No such file or directory: 'database_auth.json'
 * Serving Flask app "sendmail" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 184-771-810
127.0.0.1 - - [14/Jan/2020 09:47:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 09:47:00] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Jan/2020 13:32:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 13:33:18] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:11:10] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:11:51] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:02] "POST /addDetails HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/storage/emulated/0/Download/email_recruiter_app/sendmail.py", line 83, in addDetails
    yag.send(email, default_subject, html_msg)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/yagmail/sender.py", line 147, in send
    self.login()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/yagmail/sender.py", line 246, in login
    self._login(self.credentials)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/yagmail/sender.py", line 204, in _login
    self.smtp.login(self.user, password)
  File "/data/data/com.termux/files/usr/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/data/data/com.termux/files/usr/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/data/data/com.termux/files/usr/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b42sm17349460pjc.27 - gsmtp')
127.0.0.1 - - [14/Jan/2020 18:16:02] "GET /addDetails?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:02] "GET /addDetails?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:02] "GET /addDetails?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:03] "GET /addDetails?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:03] "GET /addDetails?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:03] "GET /addDetails?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [14/Jan/2020 18:16:51] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 17:46:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 17:46:44] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 17:47:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 20:37:12] "GET /delete_form HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 20:37:28] "POST /delete HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 20:37:30] "GET /application_details HTTP/1.1" 200 -
127.0.0.1 - - [15/Jan/2020 20:37:31] "GET /index_get_data?_=1579100851181 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/storage/emulated/0/Download/email_recruiter_app/sendmail.py", line 116, in stuff
    import requests
ModuleNotFoundError: No module named 'requests'
127.0.0.1 - - [16/Jan/2020 17:07:37] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2020 17:11:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2020 17:11:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [16/Jan/2020 19:59:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2020 06:19:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Jan/2020 06:19:59] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Jan/2020 07:01:32] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jan/2020 07:01:32] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [18/Jan/2020 07:01:34] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jan/2020 07:02:27] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [18/Jan/2020 12:28:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jan/2020 12:29:42] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [18/Jan/2020 15:26:07] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 18:07:20] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [20/Jan/2020 18:07:20] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Jan/2020 18:07:59] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [21/Jan/2020 17:00:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Jan/2020 17:02:05] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 05:07:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 05:07:23] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [22/Jan/2020 05:07:55] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 17:17:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 17:18:26] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 17:19:51] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 17:20:28] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [22/Jan/2020 17:21:27] "GET / HTTP/1.1" 200 -
 * Serving Flask app "sendmail" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 229-459-255
127.0.0.1 - - [23/Jan/2020 17:07:54] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 17:08:34] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 17:22:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 17:23:14] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 17:25:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 17:26:31] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [23/Jan/2020 19:26:43] "GET / HTTP/1.1" 200 -
 * Serving Flask app "sendmail" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 226-253-481
127.0.0.1 - - [24/Jan/2020 05:04:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2020 05:04:53] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2020 12:16:27] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2020 12:19:37] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [24/Jan/2020 17:39:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 18:10:43] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 18:10:45] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [26/Jan/2020 18:11:44] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 18:11:49] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2020 18:13:20] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 15:01:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 15:09:39] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [27/Jan/2020 15:31:25] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2020 10:06:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2020 10:06:53] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [28/Jan/2020 10:07:01] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Jan/2020 12:05:22] "POST /addDetails HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2020 04:36:53] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Jan/2020 04:37:22] "POST /addDetails HTTP/1.1" 200 -
 * Serving Flask app "plot" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5002/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 160-047-265
111.93.173.178 - - [13/Feb/2020 07:43:06] "[37mGET / HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:06] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:06] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:06] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:06] "[37mGET /_dash-component-suites/dash_core_components/async~dropdown.v1_8_0m1580836772.js HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:07] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:17] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:23] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:23] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:23] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:23] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:24] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:27] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:27] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:28] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:29] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:29] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:29] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:31] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:38] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:41] "[37mGET / HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:45] "[37mGET /_dash-dependencies HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:45] "[37mGET /_dash-layout HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:45] "[37mGET /_favicon.ico?v=1.9.0 HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:45] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
111.93.173.178 - - [13/Feb/2020 07:43:50] "[37mPOST /_dash-update-component HTTP/1.1[0m" 200 -
